version: 0.2

phases:
  post_build:
    commands:
      - echo Syncing contents to S3
      - export LC_ALL=C.UTF-8
      - aws s3 sync . "s3://${S3_BUCKET_NAME}" --exclude '.git/*'
      - echo Finished sync to S3.
      - echo Invalidating CloudFront Cache
      - aws cloudfront create-invalidation --distribution-id "${CF_DISTRIBUTION_ID}" --paths '/*'
      - echo Finished invalidating CloudFront Cache
